---
- hosts: all
  sudo: True
  sudo_user: root
  vars:
     muninaddress: '*'
     muninport: 81
     munin_subdomain: munin
  vars_prompt:
   - name: "mysql_root_password"
     prompt: "Enter MySQL password"
     private: yes
   - name: "munin_url"
     prompt: "Product release version"
     private: no     
  tasks:
     #- include: tasks/update.yml 
     #- include: tasks/common.yml 
     #- include: tasks/devtools.yml 
     - include: tasks/munin.yml 
     - include: tasks/webserver.yml
     #- include: tasks/gmailrelay.yml 
     
 
  handlers:
     - include: handlers/webserver.yml 
     - include: handlers/munin.yml 
