---
- hosts: all
  sudo: True
  sudo_user: root

  vars:
     muninaddress: '*'
     muninport: 81
     munin_subdomain: munin
     mysql_root_password: ChangeMeNow

  vars_prompt:
   - name: "gmail_domain"
     prompt: "Mail Domain"
     private: no
   - name: "gmail_user"
     prompt: "GMail User Name"
     private: no
   - name: "gmail_password"
     prompt: "GMail Password"
     private: no

  tasks:
  - include: tasks/update.yml
  - include: tasks/common.yml
  - include: tasks/devtools.yml 
  - include: tasks/munin.yml 
  - include: tasks/webserver.yml
  - include: tasks/gmailrelay.yml 

  handlers:
  - include: handlers/webserver.yml 
  - include: handlers/munin.yml
