     - name: Some common software should be installed
       action: apt pkg=$item state=latest
       with_items:
          - facter
          - vim 
          - sudo
          - locales
          - locate
          - telnet
          - openssh-server
          - ssh
          - exim4
          - tar
          - bzip2
       tags: common  

     - name: Set the timezone
       action: command /bin/echo ${timezone} > /etc/timezone  
       tags: common  

     - name: Set the timezone
       action: command dpkg-reconfigure -f noninteractive tzdata 
       tags: common