     - name: Monitoring via munin will be installed
       action: apt pkg=$item state=installed
       with_items:
          - munin
          - munin-node
          - munin-plugins-extra
          - libio-all-lwp-perl
       tags: monitoring 

     - name: Set munin-node config file
       action: template src=templates/munin.conf.j2 dest=/etc/munin/munin-node.conf owner=root group=root mode=0755
       notify: restart munin
       tags: monitoring 

     - name: Set up nginx config for munin  
       action: template src=templates/munin.nginx.j2 dest=/etc/nginx/sites-available/${munin_subdomain}.conf owner=root group=root mode=0755
       tags: monitoring 
       
     - name: Munin should be running
       action: service name=munin state=running
       tags: monitoring 