     - name: PHP5 | PHP should be installed
       action: apt pkg=$item state=latest
       with_items:
          - php5
          - php5-cli
          - php5-fpm
          - php5-curl 
          - php5-gd 
          - php5-mysql 
          - php5-mcrypt
          - php5-snmp
          - php5-imap
          - php5-memcache
          - php5-xmlrpc
       tags: php
    
     - name: PHP5 | Set php-fpm for nginx config file and restart nginx/php5-fpm
       action: template src=templates/nginx_php-fpm.conf.j2 dest=/etc/nginx/nginx_php-fpm.conf owner=root group=root mode=0755
       notify: 
          - restart nginx
          - restart php5-fpm
       tags: php 