     - name: PHP should be installed
       action: apt pkg=$item state=latest
       with_items:

          - php5
          - php-pear
          - php5-cli
          - php5-fpm
          - php5-mcrypt
       tags: php