     - name: Security | Hardening packages
       action: apt pkg=$item state=latest
       with_items:
          - fail2ban
          - logwatch
       tags: secure

     - name: Security | Disallow root SSH access
       action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
       notify: Restart sshd
       tags: secure

     - name: Security | Make logwatch mail $logwatch_email daily
       action: lineinfile dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto $logwatch_email --detail high" state=present create=yes
       tags: secure