     - name: Webserver should be installed
       action: apt pkg=$item state=installed
       with_items:
          - nginx
       notify:
          - restart nginx

     - name: Webserver should be running
       action: service name=nginx state=running